"""Native-grid research exports. No DICOM SEG or clinical signing is implied."""

import hashlib
import json
from pathlib import Path
import shutil
import tempfile
import zipfile

import numpy as np
import SimpleITK as sitk
from fastapi import HTTPException
from fastapi.responses import FileResponse
from starlette.background import BackgroundTask

from app.services.lung_geometry import same_grid


def sha256(path):
    with Path(path).open("rb") as stream:
        return hashlib.file_digest(stream, "sha256").hexdigest()


def write_slicer_mask(mask, path, nodules=None):
    output = sitk.Image(mask)
    for key in output.GetMetaDataKeys():
        output.EraseMetaData(key)
    from app.services.nodules import summarize_nodules
    if nodules is None:
        nodules = [{"id": "Lesion_1", "label": 1, "name": "Lesion mask", "color": [104, 237, 182]}]
    nodules = summarize_nodules(sitk.GetArrayViewFromImage(mask), nodules, mask.GetSpacing())
    fields = {"Segmentation_MasterRepresentation": "Binary labelmap",
              "Segmentation_ContainedRepresentationNames": "Binary labelmap|",
              "Segmentation_ReferenceImageExtentOffset": "0 0 0"}
    for index, nodule in enumerate(nodules):
        if not nodule["voxel_count"]:
            raise ValueError("Cannot export an empty nodule as a completed segment")
        prefix = f"Segment{index}_"
        fields.update({prefix + "ID": nodule["id"], prefix + "Name": nodule["name"],
                       prefix + "NameAutoGenerated": "0", prefix + "ColorAutoGenerated": "0",
                       prefix + "Color": " ".join(str(value / 255) for value in nodule["color"]),
                       prefix + "Layer": "0", prefix + "LabelValue": str(nodule["label"]),
                       prefix + "Extent": " ".join(str(value) for value in nodule["extent_xyz"])})
    for key, value in fields.items():
        output.SetMetaData(key, value)
    sitk.WriteImage(output, str(path), useCompression=True)


def export_case_files(format, mask_path, ct_path, dicom_path, provenance):
    name = f"oncometra-{provenance['study_id']}-v{provenance['version']}"
    headers = {"Cache-Control": "no-store"}
    if format == "dicom":
        if not dicom_path.is_file():
            raise HTTPException(404, "No original DICOM was imported for this case")
        return FileResponse(dicom_path, filename=name + "-original-dicom.zip", headers=headers)
    if format == "nifti":
        return FileResponse(mask_path, filename=name + "-segmentation.nii.gz", headers=headers)

    directory = Path(tempfile.mkdtemp(prefix="lung-export-"))
    try:
        mask = sitk.ReadImage(str(mask_path))
        ct = sitk.ReadImage(str(ct_path))
        same_grid(mask, ct)
        if not np.any(sitk.GetArrayViewFromImage(mask)):
            raise HTTPException(422, "The saved lesion mask is empty")
        nrrd = directory / "segmentation.seg.nrrd"
        nodules = provenance["nodules"]
        write_slicer_mask(mask, nrrd, nodules)
        if format == "nrrd":
            result, filename = nrrd, name + ".seg.nrrd"
        else:
            manifest = {"schema_version": 2, **provenance,
                        "identity_mode": provenance.get("identity_mode", "self_selected_test_not_authenticated"),
                        "scope": "Non-overlapping nodule labels; research use only. Not a clinical sign-off.",
                        "geometry": {"size_xyz": ct.GetSize(), "spacing_xyz_mm": ct.GetSpacing(),
                                     "origin_xyz_lps_mm": ct.GetOrigin(), "direction_lps": ct.GetDirection()},
                        "labels": {"0": "background", **{str(n["label"]): n["id"] for n in nodules}}, "files": {}}
            files = {"image.nii.gz": Path(ct_path), "segmentation.nii.gz": Path(mask_path),
                     "segmentation.seg.nrrd": nrrd}
            (directory / "nodules").mkdir()
            for nodule in nodules:
                binary = sitk.Cast(mask == nodule["label"], sitk.sitkUInt8)
                path = directory / "nodules" / f"{nodule['id']}.nii.gz"
                sitk.WriteImage(binary, str(path), useCompression=True)
                files[f"nodules/{nodule['id']}.nii.gz"] = path
            if dicom_path.is_file():
                files["original-dicom.zip"] = dicom_path
            manifest["files"] = {name: {"sha256": sha256(path)} for name, path in files.items()}
            result, filename = directory / "case.zip", name + "-case.zip"
            with zipfile.ZipFile(result, "w", compression=zipfile.ZIP_STORED) as archive:
                for entry, path in files.items():
                    archive.write(path, entry)
                archive.writestr("manifest.json", json.dumps(manifest, indent=2))
                archive.writestr("README.txt", (
                    "Extract this package before use.\n"
                    "3D Slicer: add image.nii.gz as a volume and segmentation.seg.nrrd as a segmentation.\n"
                    "ITK-SNAP: open image.nii.gz as the main image, then segmentation.nii.gz as segmentation.\n"
                    "Masks and CT retain the same physical grid. In the combined mask, label n identifies Nn; 0 is background.\n"
                    "The nodules/ folder contains individual binary masks (1=selected nodule) named by stable nodule ID.\n"
                    "Slicer segments retain distinct IDs, names, label values and display colors. See manifest.json.\n"
                    "If present, extract original-dicom.zip to import the original DICOM series.\n"
                    "Original DICOM contains no edited mask. The edited mask is in the separate segmentation files.\n"
                    "This package is not a DICOM SEG or RTSTRUCT export.\n"
                    "Check orientation, alignment and boundaries in the receiving application.\n"
                    "See manifest identity_mode and review history for authentication and approval provenance.\n"
                    "See manifest.json for the exported status, immutable revision and file hashes.\n"
                ))
        return FileResponse(result, filename=filename, headers=headers,
                            background=BackgroundTask(shutil.rmtree, directory, ignore_errors=True))
    except Exception:
        shutil.rmtree(directory, ignore_errors=True)
        raise
